heat_template_version: ocata

description:

parameters:

  name:
    type: string

  network_cidr:
    type: string
    constraints:
      - custom_constraint: net_cidr

  dns_nameservers:
    type: comma_delimited_list
    default: []

  host_routes:
    type: json
    default: []
    
  public_network:
    type: string
    constraints:
      - custom_constraint: neutron.network

resources:

  network:
    type: Custom::Tenant::Network
    properties:
      name: { get_param: name }
      
  subnet:
    type: Custom::Tenant::Subnet
    properties:
      name: { get_param: name }
      cidr: { get_param: network_cidr }
      network_id: { get_attr: [ network, network_id ] }
      dns_nameservers: { get_param: dns_nameservers }
      host_routes: { get_param: host_routes }
      
  router:
    type: Custom::Tenant::Router
    properties:
      name: { get_param: name }
      public_network: { get_param: public_network }

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_attr: [ router, router_id ] }
      subnet: { get_attr: [ subnet, subnet_id ] }

outputs:

  network_id:
    value: { get_attr: [ network, network_id ] }

  subnet_id:
    value: { get_attr: [ subnet, subnet_id ] }
    
  router_id:
    value: { get_attr: [ router, router_id ] }