heat_template_version: ocata

description:

parameters:

  name:
    type: string
    description: Name of the router
    constraints:
      - allowed_pattern: "[a-z][a-z0-9-]{1,}"

  public_network:
    type: string
    description: The public network to connect to
    constraints:
      - custom_constraint: neutron.network

resources:

  router:
    type: OS::Neutron::Router
    properties:
      name:
        list_join: [ '-', [{ get_param: name }, 'router'] ]
      external_gateway_info:
        network: { get_param: public_network }

outputs:

  router_id:
    value: { get_resource: router }
    
  router_admin_state_up:
    value: { get_attr: [ router, admin_state_up ] }
    
  router_external_gateway_info:
    value: { get_attr: [ router, external_gateway_info ] }
    
  router_name:
    value: { get_attr: [ router, name ] }
    
  router_status:
    value: { get_attr: [ router, status ] }
    
  router_tenant_id:
    value: { get_attr: [ router, tenant_id ] }