heat_template_version: ocata

description:

parameters:

  cidr:
    type: string
    description: The IP subnet to use in CIDR notation
    constraints:
      - custom_constraint: net_cidr

  dns_nameservers:
    type: comma_delimited_list
    description: A list of DNS servers to propagate via DHCP
    default:
      - 8.8.8.8
      - 8.8.4.4

  host_routes:
    type: json
    description: A list of host routes to propagate in the subnet
    default: []

  enable_dhcp:
    type: boolean
    default: True
    
  name:
    type: string
    description: Name to be used for network and subnet
    constraints:
      - allowed_pattern: "[a-z][a-z0-9-]{1,}"
    
  network_id:
    type: string

resources:

  subnet:
    type: OS::Neutron::Subnet
    properties:
      name:
        list_join: [ '-', [{ get_param: name }, 'subnet'] ]
      network: { get_param: network_id }
      cidr: { get_param: cidr }
      dns_nameservers: { get_param: dns_nameservers }
      host_routes: { get_param: host_routes }
      enable_dhcp: { get_param: enable_dhcp }

outputs:

  subnet_id:
    value: { get_resource: subnet }

  subnet_allocation_pools:
    value: { get_attr: [ subnet, allocation_pools ] }

  subnet_cidr:
    value: { get_attr: [ subnet, cidr ] }

  subnet_dns_nameservers:
    value: { get_attr: [ subnet, dns_nameservers ] }

  subnet_enable_dhcp:
    value: { get_attr: [ subnet, enable_dhcp ] }

  subnet_gateway_ip:
    value: { get_attr: [ subnet, gateway_ip ] }

  subnet_host_routes:
    value: { get_attr: [ subnet, host_routes ] }

  subnet_ip_version:
    value: { get_attr: [ subnet, ip_version ] }

  subnet_name:
    value: { get_attr: [ subnet, name ] }

  subnet_network_id:
    value: { get_attr: [ subnet, network_id ] }

  subnet_tenant_id:
    value: { get_attr: [ subnet, tenant_id ] }